name: Create repos as clones of base

on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Number of demo repos to create'
        required: true

env:
  REPO_COUNT: ${{ inputs.number }}

jobs:
  set-n-repos:
    needs: []
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set-repos.outputs.repos }}
    steps:
      - uses: actions/checkout@v6

      - name: Set repo names
        id: set-repos
        env:
          REPOS_FILENAME: temp.json
        run: |
          URL=https://raw.githubusercontent.com/kosli-demo/base/refs/heads/main/data/all-repos.json
          curl --fail --output ${REPOS_FILENAME} --silent "${URL}"
          FILTER=".[:${REPO_COUNT}]"
          REPOS="$(jq --compact-output ${FILTER} ${REPOS_FILENAME})"
          echo "repos=${REPOS}" >> ${GITHUB_OUTPUT}


  create-n-repos:
    needs: [set-n-repos]
    if: ${{ needs.set-n-repos.outputs.repos != '[]' }}
    strategy:
      matrix:
        include: ${{ fromJSON(needs.set-n-repos.outputs.repos) }}
    steps:
      - name: Clone Repo if it doesn't already exist
        env:
          REPO_NAME: ${{ matrix.repo_name }}
          GH_TOKEN: ${{ secrets.CLONE_PUSH_REPOS }}
        run: |
          HTTP_CODE="$(curl -s -o /dev/null -I -w "%{http_code}" https://github.com/kosli-demo/${REPO_NAME})"
          if [ "${HTTP_CODE}" != '200' ]; then
            gh repo create kosli-demo/${REPO_NAME} --public || true
            git clone --mirror https://x-access-token:${GH_TOKEN}@github.com/kosli-demo/base.git
            cd base.git
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/kosli-demo/${REPO_NAME}.git
            git push --mirror
          fi
