name: Ensure repo exists

on:
  workflow_call:
    inputs:
      repo_name:
        type: string
        required: true
    secrets:
      CLONE_PUSH_REPOS:
        required: true

jobs:
  ensure-repo-exists:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ inputs.repo_name }}
      GH_TOKEN: ${{ secrets.CLONE_PUSH_REPOS }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.event.sender.login }}@users.noreply.github.com"

      - name: Ensure repo exists
        run: |
          if ! gh repo view "kosli-demo/${REPO_NAME}" > /dev/null 2>&1; then
            # Repo does not exist so create it
            gh repo create "kosli-demo/${REPO_NAME}" --public

            # Wait for repo creation to finish
            for i in $(seq 1 10); do
              if gh repo view "kosli-demo/${REPO_NAME}" > /dev/null 2>&1; then
                break
              fi
              echo "Waiting for repo to be available (attempt ${i}/10)..."
              sleep 10
              if [ "${i}" -eq 10 ]; then
                echo "Repo kosli-demo/${REPO_NAME} not available after 10 attempts"
                exit 1
              fi
            done

            # Initialise with a clone of base
            gh repo clone "kosli-demo/${REPO_NAME}"
            mv "${REPO_NAME}"/.git /tmp
            gh repo clone kosli-demo/base
            cd base
            rm -rf .git
            mv /tmp/.git .
            TIMESTAMP="$(date +%s)"
            echo "${REPO_NAME} ${TIMESTAMP}" > ./source/datetime.txt
            git add .
            git commit --message "Initial commit"
            git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/kosli-demo/${REPO_NAME}.git"
            git push -u origin main
          fi
