name: Main

on:
  push:
    branches:
      - main
  #schedule: 
  #  - cron: '* * * * *' # Max, every 5 minutes

env:
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
  KOSLI_DEBUG:     false
  KOSLI_DRY_RUN:   false
  KOSLI_HOST:      https://staging.app.kosli.com
  KOSLI_ORG:       kosli-demo
  KOSLI_FLOW:      ${{ github.event.repository.name }}-ci
  KOSLI_TRAIL:     ${{ github.sha}}

jobs:
  setup:
    needs: []
    if: ${{ github.event.repository.name != 'spreader' }}
    runs-on: ubuntu-latest
    outputs:
      repo_json: ${{ steps.set-repo-json.outputs.repo_json }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v6

      - name: Setup repo json
        id: setup-repo-json
        run: |
          REPO="${{ github.event.repository.name }}"
          echo "REPO=:${REPO}:"
          FILTER=".[] | select(.repo_name == \"${REPO}\")"
          echo "FILTER=:${FILTER}:"
          REPO_JSON="$(jq --compact-output "${FILTER}" data/all-repos.json)"
          echo "REPO_JSON=:${REPO_JSON}:"
          echo "repo_json=${REPO_JSON}" >> ${GITHUB_OUTPUT}

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create Kosli Flow
        run:
          kosli create flow "${KOSLI_FLOW}"

      - name: Begin Kosli Trail
        run:
          kosli begin trail "${KOSLI_TRAIL}"

      - name: Write Trail URL to GitHub Step Summary
        run: |
          url="${KOSLI_HOST}/${KOSLI_ORG}/flows/${KOSLI_FLOW}/trails/${KOSLI_TRAIL}"
          echo "[Kosli Trail](${url})" > "${GITHUB_STEP_SUMMARY}"


  build:
    needs: [setup]
    runs-on: ubuntu-latest
    env:
      REPO_JSON: ${{ toJSON(needs.setup.outputs.repo_json) }}
    steps:
      # - name: Harden Runner
      #   uses: step-security/harden-runner@v2
      #   with:
      #     egress-policy: audit

      # - uses: actions/checkout@v6

      - name: Print repo json
        run:
          jq . <<< "${REPO_JSON}"

      # - name: Build docker image
      #   run:
      #     make image

      # - name: Setup Kosli CLI
      #   uses: kosli-dev/setup-cli-action@v2
      #   with:
      #     version: ${{ vars.KOSLI_CLI_VERSION }}

      # - name: Attest docker image
      #   run:
      #     kosli attest artifact 
