name: Main cronjob stochastic committer

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch: {}

jobs:
  run:
    uses: ./.github/workflows/main.yml
    with:
      scope: staging
      repo_count: 200
      repo_chance: 5
    secrets:
      CLONE_PUSH_REPOS: ${{ secrets.CLONE_PUSH_REPOS }}
      KOSLI_API_TOKEN_STAGING: ${{ secrets.KOSLI_API_TOKEN_STAGING }}
      KOSLI_API_TOKEN_PROD: ${{ secrets.KOSLI_API_TOKEN_PROD }}
