name: Main

on:
  push:
    branches:
      - main
  #schedule: 
  #  - cron: '* * * * *' # Max, every 5 minutes

jobs:
  set-some-repos:
    needs: []
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set-repos.outputs.repos }}
    steps:
      - uses: actions/checkout@v6

      - name: Set repo names
        id: set-repo-names
        env:
          REPOS_FILENAME: repos.json
        run: |
          URL=https://raw.githubusercontent.com/kosli-demo/base/refs/heads/main/data/all-repos.json
          curl --fail --output temp.json --silent "${URL}"
          ./bin/add-repo-exists.py 3 temp.json > "${REPOS_FILENAME}"
          REPOS="$(jq --compact-output . ${REPOS_FILENAME})"
          echo "repos=${REPOS}" >> ${GITHUB_OUTPUT}


  repo-names:
    needs: [set-some-repos]
    if: ${{ needs.set-some-repos.outputs.repos != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.set-some-repos.outputs.repos) }}
    uses: ./.github/workflows/repo_existence.yml
    with:
      repo_name:   ${{ matrix.repo_name }}
      repo_exists: ${{ matrix.repo_exists }}
