name: Ensure repo exists

on:
  workflow_call:
    inputs:
      repo_name:
        description: "Name of repository in kosli_demo Org"
        required: true
        type: string
      repo_exists:
        description: "Whether repo already exists or not"
        required: true
        type: string

env:
  REPO_NAME: ${{ inputs.repo_name }}

jobs:
  repo-does-not-exist:
    if: ${{ inputs.repo_exists == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        env:
          GH_TOKEN: ${{ secrets.CLONE_PUSH_REPOS }}
        run: |
          gh repo create kosli-demo/${REPO_NAME} --public || true
          git clone --mirror https://x-access-token:${GH_TOKEN}@github.com/kosli-demo/base.git
          cd base.git
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/kosli-demo/${REPO_NAME}.git
          git push --mirror

      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: ./.github/workflows/repo_change.yml
        with:
          repo_name: ${{ inputs.repo_name }}


  repo-exists:
    if: ${{ inputs.repo_exists == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: ./.github/workflows/repo_change.yml
        with:
          repo_name: ${{ inputs.repo_name }}
