name: Simulate a commit on one repo

on:
  workflow_call:
    inputs:
      repo_name:
        description: "Name of repository in kosli_demo Org"
        required: true
        type: string
    secrets:
      clone_push_repos:
        required: true

env:
  REPO_NAME: ${{ inputs.repo_name }}

jobs:
  commit-to-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: kosli-demo/${{ inputs.repo_name }}
          token: ${{ secrets.clone_push_repos }}
          fetch-depth: 0
          ref: 'main'

      - name: Make a change
        run: |
          DATE_TIME="$(date +%Y-%m-%dT%H.%M.%S)"
          echo "${DATE_TIME}" >> .github/workflows/force-ci-run

      # - name: Commit and push
      #   env:
      #     GH_TOKEN: ${{ secrets.clone_push_repos }}
      #   run: |
      #     git config --global user.name "${{ github.actor }}"
      #     git config --global user.email "${{ github.event.sender.login }}@users.noreply.github.com"
      #     git add .
      #     git commit --message "Testing spreader"
      #     git push
