name: Spreader

on:
  push:
    branches:
      - main
  #schedule: 
  #  - cron: '* * * * *' # Max, every 5 minutes

jobs:
  set-repo-names:
    needs: []
    if: ${{ github.event.repository.name == 'spreader' }}
    runs-on: ubuntu-latest
    outputs:
      repo_names: ${{ steps.set-repo-names.outputs.repo_names }}
    steps:
      - uses: actions/checkout@v6

      - name: Set repo names
        id: set-repo-names
        env:
          REPOS_FILENAME: repos.json
        run: |
          jq '.[:2]' data/all-repos.json > "${REPOS_FILENAME}"
          REPO_NAMES="$(jq --compact-output . ${REPOS_FILENAME})"
          jq . <<< "${repo_names}"
          echo "repo_names=${REPO_NAMES}" >> ${GITHUB_OUTPUT}


  repo-names:
    needs: [set-repo-names]
    if: ${{ needs.set-repo-names.outputs.repo_names != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.set-repo-names.outputs.repo_names) }}
    env:
      REPO_JSON: ${{ toJSON(matrix) }}
    steps:
      - uses: actions/checkout@v6

      - name: Clone
        env:
          GH_TOKEN: ${{ secrets.CLONE_PUSH_REPOS }}
          REPO_NAME: ${{ matrix.repo_name }}
        run: |
          gh repo create kosli-demo/${REPO_NAME} --public || true
          git clone --mirror https://x-access-token:${GH_TOKEN}@github.com/kosli-demo/spreader.git
          cd spreader.git
          echo "XXX" > x.txt
          git add .
          git commit -m "Testing"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/kosli-demo/${REPO_NAME}.git
          #git push --mirror
